"""pricer — option pricing & risk engine with a C++ core.

Thin Python package over the compiled ``_pricer`` extension. Example::

    import pricer
    c = pricer.black_scholes_call(100, 100, 0.05, 0.20, 1.0)
    g = pricer.black_scholes_greeks(pricer.OptionType.Call, 100, 100, 0.05, 0.20, 1.0)
    iv = pricer.implied_vol(pricer.OptionType.Call, c, 100, 100, 0.05, 1.0)
"""
from ._pricer import (  # noqa: F401
    OptionType,
    AverageType,
    BarrierType,
    Greeks,
    RiskMeasures,
    Position,
    BookGreeks,
    DiscountCurve,
    SurvivalCurve,
    ExposureProfile,
    SabrParams,
    SabrFit,
    black_scholes_price,
    black_scholes_call,
    black_scholes_put,
    black_scholes_greeks,
    implied_vol,
    mc_price,
    mc_price_parallel,
    mc_price_simd,
    mc_price_parallel_simd,
    qmc_price,
    book_greeks_aad,
    var_es,
    european_exposure_profile,
    cva,
    dva,
    bcva,
    geometric_asian_price,
    asian_price_mc,
    barrier_price,
    barrier_price_mc,
    lookback_floating_price,
    lookback_floating_price_mc,
    sabr_implied_vol,
    sabr_black_price,
    calibrate_sabr,
    sabr_price_mc,
    __version__,
)

__all__ = [
    "OptionType",
    "AverageType",
    "BarrierType",
    "Greeks",
    "RiskMeasures",
    "Position",
    "BookGreeks",
    "DiscountCurve",
    "SurvivalCurve",
    "ExposureProfile",
    "SabrParams",
    "SabrFit",
    "black_scholes_price",
    "black_scholes_call",
    "black_scholes_put",
    "black_scholes_greeks",
    "implied_vol",
    "mc_price",
    "mc_price_parallel",
    "mc_price_simd",
    "mc_price_parallel_simd",
    "qmc_price",
    "book_greeks_aad",
    "var_es",
    "european_exposure_profile",
    "cva",
    "dva",
    "bcva",
    "geometric_asian_price",
    "asian_price_mc",
    "barrier_price",
    "barrier_price_mc",
    "lookback_floating_price",
    "lookback_floating_price_mc",
    "sabr_implied_vol",
    "sabr_black_price",
    "calibrate_sabr",
    "sabr_price_mc",
    "__version__",
]
